# order is critical for model
classes:
  - mixer
  - game
  - user
  
model:
  class: random_forest
  max_depth: 3

# only for inference
preprocess: null

train:
  metrics:
    - acc
    - TP
    - FN
    - FP
  pretrained: null
  # only for iterative training
  loss:
    class: cross_entropy
  opt: Adam
  learning_rate: 0.001
  weight_decay: 0.005
  grad_norm: 1.0


test:
  step_metrics:  # only scalars
    - acc
    - TP
    - FN
    - FP
  # for total test set
  sum_metrics:
    - acc
    - precision
    - recall
    - conf_matrix
  # via manager
  plot_conf_matrix: False
  plot_pr: False   # Precision-Recall curve
  plot_roc: False  # ROC curve

manager:
  clearml:
    key_token: R5V25ELMF8K44HN6ZDP8
    secret_token: QJPm5a8Ef4L7Ag5QRuemh93RFEXHSdXaxnkwhM0dRwa0mtf9qE
    subproject: True  # experiment format
  hparams:
    train:
      learning_rate: 0.001
