n_classes: &n_classes 2

model:
  cnn:
    n_classes: *n_classes
    n_layers: 3
    fdim: 256

loss: 
  cross_entropy:
    pos_weight: [0.8, 0.2]

test:
  metrics: ["TP", "FN", "FP", "TN"]

preprocess: &preprocess
  sample_rate: 16000
  fdim: 256

data:
  preprocess: *preprocess
  n_classes: *n_classes

train:
  model: cnn
  loss: cross_entropy
  metrics: ["TP", "FN"]
  opt: Adam
  learning_rate: 0.0001
  weight_decay: 0.00001  # reg loss
  grad_norm: 1.0