n_classes: &n_classes 2

model:
  cnn:
    n_classes: *n_classes
    n_layers: &cnn_layers 3
    fdim: 256
    weights: 'dev/experiments/experiment2/train/002/weights/2.pt'

loss: 
  cross_entropy:
    pos_weight: [0.8, 0.2]

test:
  model: cnn
  metrics: ["CrossEntropyLoss", "TP", "FN", "FP", "TN"]
  loss: cross_entropy

preprocess: &preprocess
  sample_rate: 16000
  fdim: 256

manager:
  mlflow:
    url: http://192.168.11.181:3500
  clearml:
    key_token: R5V25ELMF8K44HN6ZDP8
    secret_token: QJPm5a8Ef4L7Ag5QRuemh93RFEXHSdXaxnkwhM0dRwa0mtf9qE
    subproject: False  # experiment format
  hparams:
    cnn_layers: *cnn_layers

data:
  preprocess: *preprocess
  n_classes: *n_classes

train:
  model: cnn
  loss: cross_entropy
  metrics: ["CrossEntropyLoss", "TP", "FN"]
  opt: Adam
  learning_rate: 0.0001
  weight_decay: 0.00001  # reg loss
  grad_norm: 1.0
  pretrained: ''