n_classes: &n_classes 2
frame: &frame 0.2  # classificated frame len (sec)
sample_rate: &sr 8000

# -------------------- Architectures --------------------
# valid models
models:
  tcn:
    timesteps: 26             # T
    in_channels: 40           # F
    channels: [64, 32, 16]    # 4 TempBlocks
    hidden_dim: 100
    n_classes: *n_classes
    kernel_size: 5
    dropout: 0.1
    weights: './dev/models/Mar04_initial-and-pseudo-data_003/weights/ep_10.pt'
    features:  # {'name': {params}} or null
      logmel:
        sr: *sr
        wnd_step: 0.008
        wnd_len: 0.010
        nfilt: 40   # F
        nfft: 512

model: tcn  # model 

loss: 
  cross_entropy:
    weights: [0.8, 0.2]

test:
  metrics: ["CrossEntropyLoss", "TP", "FN", "FP", "TN"]
  loss: cross_entropy

preprocess:
  sr: *sr
  codec: pcm_s16le
  min_dur: 0.2  # sec
  max_dur: 300  # sec
  format: wav
  frame: *frame   # split on frames
  features: null  # {'name': {params}} or null
    # logmel:
    #   sr: *sr
    #   wnd_step: 0.008
    #   wnd_len: 0.010
    #   nfilt: 40   # F
    #   nfft: 512

manager:
  mlflow:
    url: http://192.168.11.181:3500
  clearml:
    key_token: R5V25ELMF8K44HN6ZDP8
    secret_token: QJPm5a8Ef4L7Ag5QRuemh93RFEXHSdXaxnkwhM0dRwa0mtf9qE
    subproject: True  # experiment format
  hparams:
    channels: [64, 32, 16]

train:
  loss: cross_entropy
  metrics: ["CrossEntropyLoss", "TP", "FN"]
  opt: Adam
  learning_rate: 0.0001
  weight_decay: 0.00001  # reg loss
  grad_norm: 1.0
  pretrained: ''