# hint: use null for None variables

# order is critical for model
n_classes: &n_classes 2
classes:
  - fake
  - real
sr: &sr 8000
  
# preprocess outside model
preprocess:
  LogmelPreprocess:  # class name
    sr: *sr
    wnd_step: 0.008
    wnd_len: 0.010
    nfilt: 40
    nfft: 512

model:
  # preprocess inside model
  preprocess: null
  TCNClassification:  # class name
    n_classes: *n_classes
    timesteps: 376            # T for 3 sec audio
    in_channels: 40           # F
    channels: [64, 32, 16]    # 3 TempBlocks
    hidden_dim: 100
    kernel_size: 5
    dropout: 0.1

loss:
  CrossEntropyLoss:
    weights: null  # null if equal

train:
  metrics:  # for each train step only scalars
    - acc
    - TP
    - FN
    - FP
  pretrained: null
  opt: &opt Adam
  learning_rate: &lr 0.001
  weight_decay: 0.005
  grad_norm: 1.0


test:
  weights: null  # default weights
  step_metrics:  # only scalars
    - acc
    - TP
    - FN
    - FP
  # for total test set
  sum_metrics:
    - acc
    - precision
    - recall
    - conf_matrix
  # via manager
  plot_conf_matrix: True
  plot_pr: True   # Precision-Recall curve
  plot_roc: True  # ROC curve


manager:
  clearml:
    key_token: R5V25ELMF8K44HN6ZDP8
    secret_token: QJPm5a8Ef4L7Ag5QRuemh93RFEXHSdXaxnkwhM0dRwa0mtf9qE
    subproject: True  # experiment format
  hparams:
    train:
      learning_rate: *lr
      opt: *opt
